pagme/urls.py
from django.urls import path
from . import views

app_name = "pagme"

urlpatterns = [
    path("", views.list, name="list_debtors" ),
    path("cadastrar/", views.create, name="create_debtor"),
    path("editar_devedor/<int:pk>/", views.update, name="update_debtor"),
    path("deletar_devedor/<int:pk>/", views.delete, name="delete_debtor"),
]

project_root/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("pagme.urls"), name="pagme"),
    #path("", include("accounts.urls"), name="accounts"),
    #path("accounts/", include('django.contrib.auth.urls')),
]

templates/template/expense/create_and_edit_debtor.html
<!-- create_debtor.html e update_debtor.html -->
{% extends "components/base_template.html" %}

{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <div class="card shadow-sm">
                <div class="card-header bg-dark text-white text-center">
                    <h2 class="mb-0">{% if object %}Editar{% else %}Cadastrar{% endif %} Devedor</h2>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            {{ form.name.label_tag }}
                            {{ form.name }}
                        </div>
                        <div class="mb-3">
                            {{ form.nickname.label_tag }}
                            {{ form.nickname }}
                        </div>
                        <div class="mb-3">
                            {{ form.value.label_tag }}
                            {{ form.value }}
                        </div>
                        <div class="mb-3">
                            {{ form.last_payment_date.label_tag }}
                            {{ form.last_payment_date }}
                        </div>
                        <div class="mb-3 form-check">
                            {{ form.is_paid }} {{ form.is_paid.label_tag }}
                        </div>
                        <button type="submit" class="btn btn-success w-100">
                            {% if object %}Atualizar{% else %}Cadastrar{% endif %}
                        </button>
                        <a href="{% url "pagme:list_debtors" %}" class="btn btn-secondary w-100 mt-3">Voltar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/template/expense/create_debtor.html
{% extends "components/base_template.html" %}

{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <div class="card shadow-sm">
                <div class="card-header bg-dark text-white text-center">
                    <h2 class="mb-0">Cadastrar Devedor e Dívida</h2>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            {{ form.name.label_tag }}
                            {{ form.name }}
                        </div>
                        <div class="mb-3">
                            {{ form.nickname.label_tag }}
                            {{ form.nickname }}
                        </div>
                        <div class="mb-3">
                            {{ form.value.label_tag }}
                            {{ form.value }}
                        </div>
                        <div class="mb-3">
                            {{ form.last_payment_date.label_tag }}
                            {{ form.last_payment_date }}
                        </div>
                        <button type="submit" class="btn btn-success w-100">Cadastrar</button>
                        <a href="{% url "pagme:peoples" %}" class="btn btn-secondary w-100 mt-3">Voltar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block javascript %}
{% comment %} <script>
    $(document).ready(function(){
        $('.datepicker').datepicker({
            format: 'yyyy-mm-dd',  // Formato da data
            autoclose: true  // Fecha o calendário após a seleção
        });
    });
</script> {% endcomment %}

{% endblock javascript %}

templates/template/expense/delete_debtors.html
{% extends 'components/base_template.html' %}
{% block title %} Deletar Devedor {% endblock %}

{% block content %}

<div class="d-flex">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-8 col-sm-10">
                <div class="card shadow-sm border-0">
                    <div class="card-header bg-danger text-white text-center">
                        <h1 class="h4 mb-0">Confirmar Exclusão</h1>
                    </div>
                    <div class="card-body p-4">
                        <p class="text-dark text-center fs-5">
                            Você tem certeza de que deseja excluir o Devedor:
                            <span class="fw-bold text-danger">"{{ debtors.name }}"</span>"?
                        </p>
                        <form method="post" action="{% url 'pagme:delete_debtor' debtors.pk %}">
                            {% csrf_token %}
                            <div class="d-flex justify-content-center gap-3">
                                <form method="POST" action="{% url 'pagme:delete_debtor' debtors.pk %}">
                                    {% csrf_token %}
                                    <button class="btn btn-danger px-4" type="submit">Excluir</button>
                                </form>
                                <a href="{% url 'pagme:list_debtors' %}" class="btn btn-secondary px-4">
                                    Cancelar
                                </a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/template/expense/list_debtors.html
{% extends "components/base_template.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-10 col-lg-8">
            {% include "components/messages.html" %}
            <div class="card shadow-lg rounded-4">
                <div class="card-header bg-dark text-white text-center py-3 rounded-top-4">
                    <h2 class="m-0">Lista de Clientes</h2>
                </div>
                <div class="card-body">
                    <div class="d-flex justify-content-between mb-3">
                        <div class="d-flex flex-column gap-2">
                            <h5 class="text-secondary">Gerencie seus clientes</h5>
                            {% if expenses %}
                            <p class="text-muted">{{ expenses.count }} Cliente(es) registrados </p>
                            {% else %}
                            
                            {% endif %}
                        </div>
                            <a href="{% url "pagme:create_debtor" %}" class="btn btn-success h-25">+ Adicionar Cliente</a>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-hover align-middle text-center">
                            <thead class="table-dark">
                                <tr>
                                    <th scope="col">Pessoa</th>
                                    <th scope="col">Apelido</th>
                                    <th scope="col">Valor da mensalidade</th>
                                    <th scope="col">Último dia que pagou</th>
                                    <th scope="col">Dias em atraso</th>
                                    <th scope="col">Ações</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% if expenses %}
                                {% for expense in expenses %}
                                <tr>
                                    <td>{{ expense.name }}</td>
                                    <td>{{ expense.nickname }}</td>
                                    <td>R$ {{ expense.value }}</td>
                                    <td>{{ expense.last_payment_date }}</td>
                                    <td>
                                        {% if expense.days_late is not None %}
                                            {{ expense.days_late }} Dias
                                        {% else %}
                                            N/A
                                        {% endif %}
                                    </td>
                                    <td>
                                        <a href="{% url 'pagme:update_debtor' expense.pk %}" class="btn btn-sm btn-info">Editar</a>
                                        <a href="{% url 'pagme:delete_debtor' expense.pk %}" class="btn btn-sm btn-danger mt-2">Excluir</a>
                                    </td>
                                </tr>
                                {% endfor %}
                                {% else %}
                                <tr>
                                    <td colspan="5" class="text-center text-muted">Nenhum devedor cadastrado.</td>
                                </tr>
                                {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/template/expense/list_peoples.html
{% extends "components/base_template.html" %}

{% block content %}
<div class="d-flex justify-content-center container mt-5">
    <div class="col-md-12">
        {% include "components/messages.html" %}
        <div class="card shadow-lg p-3">
            <div class="card-header bg-dark text-white text-center">
                <h2 class="m-0">Lista de Devedores</h2>
            </div>
            <div class="card-body">
                <a href="{% url "pagme:create_debtor" %}"class="btn btn-success">+ Adicionar Devedor</a>
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">Pessoa</th>
                            <th scope="col">Apelido</th>
                            <th scope="col">Valor da mensalidade</th>
                            <th scope="col">Último dia que pagou</th>
                            <th scope="col">Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if expenses %}
                        {% for expense in expenses %}
                        <tr>
                            <td>{{ expense.debtor.name }}</td>
                            <td>{{ expense.debtor.nickname }}</td>
                            <td>R$ {{ expense.value }}</td>
                            <td>{{ expense.days }}</td>
                            <td>
                                <a href="{% url 'pagme:update_debtor' expense.pk %}" class="btn btn-sm btn-warning">Editar</a>
                                <a href="{ url 'deletar_produto' expense.id %}" class="btn btn-sm btn-danger">Excluir</a>
                            </td>
                        </tr>
                        {% endfor %}
                        {% else %}
                        <tr>
                            <td colspan="4" class="text-center">Nenhum devedor cadastrado.</td>
                        </tr>
                        {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/template/expense/update_debtor.html
{% extends "components/base_template.html" %}

{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <div class="card shadow-sm">
                <div class="card-header bg-dark text-white text-center">
                    <h2 class="mb-0">Editar Devedor e Dívida</h2>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            {{ form.name.label_tag }}
                            {{ form.name }}
                        </div>
                        <div class="mb-3">
                            {{ form.nickname.label_tag }}
                            {{ form.nickname }}
                        </div>
                        <div class="mb-3">
                            {{ form.value.label_tag }}
                            {{ form.value }}
                        </div>
                        <div class="mb-3">
                            {{ form.last_payment_date.label_tag }}
                            {{ form.last_payment_date }}
                        </div>
                        <button type="submit" class="btn btn-success w-100">Salvar Alterações</button>
                        <a href="{% url 'pagme:list_debtor' %}" class="btn btn-secondary w-100 mt-3">Cancelar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}